site_name: Bazzite Documentation
site_author: nicknamenamenick
site_url: !ENV MKDOCS_SITE_URL
repo_url: https://github.com/ublue-os/bazzite
repo_name: ublue-os/bazzite
edit_uri: https://github.com/KyleGospo/docs.bazzite.gg/blob/main/src
site_description: Bazzite is a custom image built upon Fedora Atomic Desktops that brings the best of Linux gaming to all of your devices.

watch:
  - theme_overrides
  - &macros_tmpls macros_tmpls

validation:
  links:
    not_found: warn
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn

extra_css:
  - stylesheets/image_sizing.css
  - stylesheets/bazzite.css
theme:
  name: material
  custom_dir: theme_overrides
  palette:
    - media: "(prefers-color-scheme)"
      primary: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  favicon: static/favicon.svg
  logo: static/favicon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    # - navigation.instant # Incompatible with mkdocs_static_i18n
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
    - announce.dismiss
    - content.tabs.link

docs_dir: src
site_dir: book

hooks:
  - hooks/fail_on_hardcoded_url.py # This hook must be set before cmdrun.py, otherwise it will fail
  - hooks/cmdrun.py # 100-99
  - hooks/embed_youtube.py # 80
  - hooks/md_image_sizing.py

plugins:
  - privacy
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: French
          build: true
        - locale: cs
          name: Čeština
          build: true
        - locale: zh_HK
          name: 中文（香港）
          build: true
          site_name: Bazzite 指南
          theme:
            language: zh-Hant
          nav:
            - 主頁: index.md
            - 常見問題: "General/FAQ.md"
            - 安裝指南:
                - "安裝 Bazzite": General/Installation_Guide/index.md
                - "安裝教學": General/Installation_Guide/install-guide.md
                - "安裝後設定": General/Installation_Guide/post-installation.md
                - "安裝疑難排解": General/Installation_Guide/troubleshoot_guide.md
                - "舊版ISO安裝教學": General/Installation_Guide/legacy-install.md
                - "備用安裝辦法": General/Installation_Guide/alternate-install-guide.md
            - 遊戲指南:
                - "遊戲簡介": Gaming/index.md
                - "硬體相容性": Gaming/Hardware_compatibility_for_gaming.md
            - Bazzite掌機版(Bazzite-Deck):
                - "Bazzite掌機版教學": Handheld_and_HTPC_edition/index.md
                - "Bazzite掌機版概覽": Handheld_and_HTPC_edition/Steam_Gaming_Mode.md
                - "Steam遊戲模式的常見問題與解決辦法": Handheld_and_HTPC_edition/quirks.md
                - "掌機相容性":
                    - Handheld_and_HTPC_edition/Handheld_Wiki/index.md
                    - "華碩": Handheld_and_HTPC_edition/Handheld_Wiki/ASUS_ROG_Ally.md
                    - "聯想": Handheld_and_HTPC_edition/Handheld_Wiki/Lenovo_Legion_Go.md
                    - "GPD": Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md
                    - "OneXPlayer": Handheld_and_HTPC_edition/Handheld_Wiki/OneXPlayer_Handhelds.md
                    - "Ayn": Handheld_and_HTPC_edition/Handheld_Wiki/Ayn_Handhelds.md
                    - "Ayaneo": Handheld_and_HTPC_edition/Handheld_Wiki/Ayaneo_Handhelds.md
                    - "Steam Deck": Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md
                    - "其他掌機": Handheld_and_HTPC_edition/Handheld_Wiki/Other_Handhelds.md
            - 軟件:
                - "安裝及管理軟件":
                    - Installing_and_Managing_Software/index.md
                    - "Bazzite軟件安裝概覽": Installing_and_Managing_Software/software-intro.md
                    - "Bazzite Portal": Installing_and_Managing_Software/Bazzite_Portal.md
                    - "ujust 命令行指令": Installing_and_Managing_Software/ujust.md
                    - "Bazaar 應用程式商店": Installing_and_Managing_Software/Flatpak.md
                    - "Homebrew": Installing_and_Managing_Software/Homebrew.md
                    - "容器":
                        - Installing_and_Managing_Software/Containers.md
                        - "Distrobox": Installing_and_Managing_Software/Distrobox.md
                        - "Quadlet": Installing_and_Managing_Software/Quadlet.md
                    - "Appimage": Installing_and_Managing_Software/AppImage.md
                    - "rpm-ostree": Installing_and_Managing_Software/rpm-ostree.md
                    - "Waydroid 設置教程": Installing_and_Managing_Software/Waydroid_Setup_Guide.md
                - "系統更新與回溯":
                    - "Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/index.md"
                    - "系統更新教程": "Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/updating_guide.md"
                    - "回溯系統更新": "Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/rolling_back_system_updates.md"
                    - "切換更新頻道": "Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/rebase_guide.md"
                    - "Bazzite更新助手(bazzite-rollback-helper)": "Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/bazzite_rollback_helper.md"
            - 進階指南:
                - "目錄": Advanced/index.md
                - "設置硬盤自動掛載": Advanced/Auto-Mounting_Secondary_Drives.md
                - "使用ScopeBuddy管理Gamescope渲染器": Advanced/scopebuddy.md
                - "自定義解像度": Advanced/custom_resolution.md
                - "Bazzite 命令行工具": Advanced/bazzite-cli.md
                - "Looking-Glass指南": Advanced/looking-glass.md
                - "系統殼層(Shell)設置須知": Advanced/Best_Shell_Practices.md
                - "重啟至系統救援模式(Rescue Mode)": Advanced/rescue-and-emergency-mode.md
                - "重置用戶密碼": Advanced/Reset_Forgotten_User_Password.md
                - "設置系統內存分頁以擴展內存及啟用休眠模式": Advanced/swapfile.md
                - "系統啟動時顯示日誌輸出": Advanced/plymouth_init.md
                - "使用Sunshine進行遊戲串流": Advanced/sunshine.md
                - "如何更改Initramfs和Dracut": Advanced/dracut-and-initramfs.md
                - "創建自定義Bazzite系統映像檔": Advanced/creating_custom_image.md
            - Bazzite-DX: https://dev.bazzite.gg
            - 合作與貢獻: https://universal-blue.org/contributing.html
            - 社群: community.md
            - 捐款: donations.md
            - 下載: https://bazzite.gg/#image-picker

  - search
  - macros:
      include_dir: *macros_tmpls
  - glightbox:
      skip_classes:
        - "no-lightbox"
  - git-revision-date-localized:
      enable_creation_date: !ENV [CI, false]
      fallback_to_build_date: true
  - git-committers:
      enabled: !ENV [CI, false]
      token: !ENV ["GH_TOKEN"]
      repository: !ENV GITHUB_REPOSITORY
      branch: !ENV GITHUB_REF_NAME
  - bazzite-social:
      # use_image_from_page: true # Use first image found in a page as fallback
  - tags:
      tags_file: tags.md

markdown_extensions:
  - attr_list
  - md_in_html
  - nl2br
  - mdx_better_lists
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  #region Enable Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  #endregion Enable Admonitions
  #region Enable Content Tabs
  - pymdownx.tabbed:
      alternate_style: true
  #endregion Enable Content Tabs

nav:
  - index.md
  - FAQ: "General/FAQ.md"
  - Installation:
      - "Installing Bazzite": General/Installation_Guide/index.md
      - "Installation Guide": General/Installation_Guide/install-guide.md
      - "Post-Installation Setup": General/Installation_Guide/post-installation.md
      - "Installation Troubleshoot Guide": General/Installation_Guide/troubleshoot_guide.md
      - "Legacy ISO Installation Guide": General/Installation_Guide/legacy-install.md
      - "Alternative Installation Method": General/Installation_Guide/alternate-install-guide.md
  - General:
      - "General Guides": General/index.md
      - "Dictionary and Terminology": General/terms.md
      - "Comparison of Bazzite and Fedora Atomic Desktop": General/Fedora_Atomic_Comparison.md
      - "SteamOS Comparison": "General/SteamOS_Comparison.md"
      - "Desktop Environment Tweaks": General/Desktop_Environment_Tweaks.md
      - "VPN Setup": General/VPN.md
      - "Issues & Resolutions": "General/issues_and_resolutions.md"
      - "Reporting Bugs": General/reporting_bugs.md
      - "Community Resources": General/community-links.md
      - "Security Policy": https://github.com/ublue-os/bazzite/blob/main/SECURITY.md
      - "License": https://github.com/ublue-os/bazzite/blob/main/LICENSE
      - "Press Kit": https://github.com/ublue-os/bazzite/tree/main/press_kit
      - "Uninstalling Bazzite": General/uninstalling-bazzite.md
  - Gaming:
      - "Gaming Guides": Gaming/index.md
      - "Introduction to Gaming on Bazzite": Gaming/gaming-intro.md
      - "Hardware Compatibility for Gaming": Gaming/Hardware_compatibility_for_gaming.md
      - "Game Launchers": Gaming/Game_Launchers.md
      - "Managing & Modding Games": Gaming/Managing_and_modding_games.md
      - "Launch Options and Environment Variables": Gaming/launch-options-env-variables.md
      - "Common Gaming Issues": Gaming/Common_gaming_issues.md
  - Bazzite-Deck:
      - "Bazzite-Deck Guides": Handheld_and_HTPC_edition/index.md
      - "Bazzite-Deck General Overview": Handheld_and_HTPC_edition/Steam_Gaming_Mode.md
      - "Steam Gaming Mode Quirks and Workarounds": Handheld_and_HTPC_edition/quirks.md
      - "Handheld Compatibility":
          - Handheld_and_HTPC_edition/Handheld_Wiki/index.md
          - "ASUS Handhelds": Handheld_and_HTPC_edition/Handheld_Wiki/ASUS_ROG_Ally.md
          - "Lenovo Handhelds": Handheld_and_HTPC_edition/Handheld_Wiki/Lenovo_Legion_Go.md
          - "GPD Handhelds": Handheld_and_HTPC_edition/Handheld_Wiki/GPD_Handhelds.md
          - "OneXPlayer Handhelds": Handheld_and_HTPC_edition/Handheld_Wiki/OneXPlayer_Handhelds.md
          - "Ayn Handhelds": Handheld_and_HTPC_edition/Handheld_Wiki/Ayn_Handhelds.md
          - "Ayaneo Handhelds": Handheld_and_HTPC_edition/Handheld_Wiki/Ayaneo_Handhelds.md
          - "Steam Deck": Handheld_and_HTPC_edition/Handheld_Wiki/Steam_Deck.md
          - "Other Handhelds": Handheld_and_HTPC_edition/Handheld_Wiki/Other_Handhelds.md
  - Software:
      - "Installing and Managing Software":
          - Installing_and_Managing_Software/index.md
          - "Introduction to Installing Software on Bazzite": Installing_and_Managing_Software/software-intro.md
          - "Bazzite Portal": Installing_and_Managing_Software/Bazzite_Portal.md
          - "ujust Commands": Installing_and_Managing_Software/ujust.md
          - "Bazaar App Store": Installing_and_Managing_Software/Flatpak.md
          - "Homebrew": Installing_and_Managing_Software/Homebrew.md
          - "Containers":
              - Installing_and_Managing_Software/Containers.md
              - "Distrobox": Installing_and_Managing_Software/Distrobox.md
              - "Quadlet": Installing_and_Managing_Software/Quadlet.md
          - "Appimage": Installing_and_Managing_Software/AppImage.md
          - "rpm-ostree": Installing_and_Managing_Software/rpm-ostree.md
          - "Waydroid Setup Guide": Installing_and_Managing_Software/Waydroid_Setup_Guide.md
      - "Updates, Rollbacks, & Rebasing":
          - "Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/index.md"
          - "Updating Guide": "Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/updating_guide.md"
          - "Rolling Back System Updates": "Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/rolling_back_system_updates.md"
          - "Rebase Guide": "Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/rebase_guide.md"
          - "Bazzite Rollback Helper": "Installing_and_Managing_Software/Updates_Rollbacks_and_Rebasing/bazzite_rollback_helper.md"
  - Advanced:
      - "Advanced Guides": Advanced/index.md
      - "Auto-Mounting Secondary Drives": Advanced/Auto-Mounting_Secondary_Drives.md
      - "Managing Gamescope Using ScopeBuddy": Advanced/scopebuddy.md
      - "Custom Resolutions": Advanced/custom_resolution.md
      - "Bazzite Command Line Tools": Advanced/bazzite-cli.md
      - "Using Looking-Glass": Advanced/looking-glass.md
      - "Best Shell Practices": Advanced/Best_Shell_Practices.md
      - "Booting to Rescue Mode": Advanced/rescue-and-emergency-mode.md
      - "Reset Forgotten User Password": Advanced/Reset_Forgotten_User_Password.md
      - "Using Swap for Additional Memory or Hibernation": Advanced/swapfile.md
      - "Show Detailed Init Logs During Boot": Advanced/plymouth_init.md
      - "Setting up Sunshine on Bazzite": Advanced/sunshine.md
      - "How to Modify Initramfs and Dracut": Advanced/dracut-and-initramfs.md
      - "Creating A Custom Bazzite Image": Advanced/creating_custom_image.md
  - Bazzite-DX: https://dev.bazzite.gg
  - Contribute: https://universal-blue.org/contributing.html
  - Community: community.md
  - Videos: https://www.youtube.com/playlist?list=PLuiT7cNvThNC956b5rtSPCjwcHe2tKBmY
  - Donate: donations.md
  - Download: https://bazzite.gg/#image-picker
